### ISSUE TITLE
saveAll without setTimeout

### ISSUE THREAD

**Issue by lsaudon** [enversecilmis/component-generator#1]
Hi,
I had the same problem as you, to edit files and save them. I found a less disgusting solution.

https://github.com/enversecilmis/component-generator/blob/0a47462d82ad1ab726f2c4a989d18521cc637d9b/src/extension.ts#L49-L54

Solution:

```typescript
await vscode.workspace.applyEdit(wsedit, { isRefactoring: true });
await vscode.workspace.saveAll();
```

**Comment by enversecilmis** [comment]
Thank you so much for this!
But it doesn't work for me. It says "applyEdit expects one arguement". I guess it's because of the version is older. So I'll look into it when I have time. Really appreciate it.

**Comment by lsaudon** [comment]
Update vscode dependency and vscode version

**Comment by lsaudon** [comment]
```
  "engines": {
    "vscode": "^1.73.1"
  },
```
`"@types/vscode": "^1.73.1",`

**Comment by enversecilmis** [comment]
Yep that works. Thanks.
